# -*- coding: utf-8 -*-
"""10 CSE HealthSec_ Cyber Protection for AI based Medical Communication

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_hwN-b-vJBjmlDAzRnY-n2ZNwLDFny9y
"""

import requests
from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt
from cryptography.fernet import Fernet
import numpy as np

# https://drive.google.com/file/d/1ezP7YI09wcxO07dDFi5USG64sosbvoDb/view?usp=sharing

# Step 1: Load the image from Google Drive URL
file_id = "1ezP7YI09wcxO07dDFi5USG64sosbvoDb"
image_url = f"https://drive.google.com/uc?export=download&id={file_id}"

response = requests.get(image_url)
response.raise_for_status()

image = Image.open(BytesIO(response.content))

# Display original image
plt.figure(figsize=(6,6))
plt.imshow(image)
plt.title("Original Image")
plt.axis('off')
plt.show()

# Step 2: Encrypt the image data
# Convert image to bytes
image_bytes = BytesIO()
image.save(image_bytes, format=image.format)
image_data = image_bytes.getvalue()

# Generate encryption key
key = Fernet.generate_key()
cipher = Fernet(key)

encrypted_data = cipher.encrypt(image_data)

# Display encrypted image as a grayscale plot of bytes values
encrypted_array = np.frombuffer(encrypted_data, dtype=np.uint8)
plt.figure(figsize=(10,2))
plt.plot(encrypted_array, color='black')
plt.title("Encrypted Image Data (Byte Representation)")
plt.xlabel("Byte Index")
plt.ylabel("Byte Value")
plt.show()



# Step 3: Decrypt the encrypted image data
decrypted_data = cipher.decrypt(encrypted_data)

# Step 4: Load decrypted bytes into a PIL Image
decrypted_image = Image.open(BytesIO(decrypted_data))

# Display decrypted image
plt.figure(figsize=(6,6))
plt.imshow(decrypted_image)
plt.title("Decrypted Image")
plt.axis('off')
plt.show()





from google.colab import drive
drive.mount('/content/drive')

import requests
from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt
from cryptography.fernet import Fernet
import numpy as np
from skimage.metrics import structural_similarity as ssim

# Step 1: Load the image from Google Drive URL
file_id = "1AVgok_S3UrCtlDvxsTc6ltAaPwcZGNMD"
image_url = f"https://drive.google.com/uc?export=download&id={file_id}"

response = requests.get(image_url)
response.raise_for_status()

image = Image.open(BytesIO(response.content))

# Display original image
plt.figure(figsize=(6,6))
plt.imshow(image)
plt.title("Original Image")
plt.axis('off')
plt.show()

# Step 2: Encrypt the image data
# Convert image to bytes
image_bytes = BytesIO()
image.save(image_bytes, format=image.format)
image_data = image_bytes.getvalue()

# Generate encryption key
key = Fernet.generate_key()
cipher = Fernet(key)

encrypted_data = cipher.encrypt(image_data)

# Display encrypted image as a grayscale plot of bytes values
encrypted_array = np.frombuffer(encrypted_data, dtype=np.uint8)
plt.figure(figsize=(10,2))
plt.plot(encrypted_array, color='black')
plt.title("Encrypted Image Data (Byte Representation)")
plt.xlabel("Byte Index")
plt.ylabel("Byte Value")
plt.show()

# Step 3: Decrypt the encrypted image data
decrypted_data = cipher.decrypt(encrypted_data)

# Step 4: Load decrypted bytes into a PIL Image
decrypted_image = Image.open(BytesIO(decrypted_data))

# Display decrypted image
plt.figure(figsize=(6,6))
plt.imshow(decrypted_image)
plt.title("Decrypted Image")
plt.axis('off')
plt.show()

# Step 5: Compare original and decrypted images

# Convert images to NumPy arrays
original_np = np.array(image)
decrypted_np = np.array(decrypted_image)

# Calculate Mean Squared Error (MSE)
mse_value = np.mean((original_np - decrypted_np) ** 2)

# Calculate Peak Signal-to-Noise Ratio (PSNR)
if mse_value == 0:
    psnr_value = float('inf')
else:
    max_pixel = 255.0
    psnr_value = 20 * np.log10(max_pixel / np.sqrt(mse_value))

# Calculate Structural Similarity Index (SSIM)
# Specify win_size=3 and channel_axis=2 for color images
ssim_value = ssim(original_np, decrypted_np, win_size=3, channel_axis=2)

print(f"MSE: {mse_value:.6f}")
print(f"PSNR: {psnr_value:.2f} dB")
print(f"SSIM: {ssim_value:.6f}")

# Optional: Display side-by-side images for visual comparison
fig, axes = plt.subplots(1, 2, figsize=(12, 6))
axes[0].imshow(image)
axes[0].set_title("Original Image")
axes[0].axis('off')

axes[1].imshow(decrypted_image)
axes[1].set_title("Decrypted Image")
axes[1].axis('off')

plt.show()

import requests
from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt
from cryptography.fernet import Fernet
import numpy as np
from skimage.metrics import structural_similarity as ssim
from sklearn.ensemble import IsolationForest

# ------------------------
# Step 1: Authentication Simulation (placeholder)
# ------------------------
def authenticate_user():
    # This should be replaced with real authentication logic
    print("Authenticating user...")
    authenticated = True
    print("Authentication successful." if authenticated else "Authentication failed.")
    return authenticated

# ------------------------
# Step 2: Load image from Google Drive
# ------------------------
def load_image_from_drive(file_id):
    image_url = f"https://drive.google.com/uc?export=download&id={file_id}"
    response = requests.get(image_url)
    response.raise_for_status()
    image = Image.open(BytesIO(response.content))
    return image

# ------------------------
# Step 3: Encrypt and decrypt image data
# ------------------------
def encrypt_image_data(image, cipher):
    image_bytes = BytesIO()
    image.save(image_bytes, format=image.format)
    encrypted_data = cipher.encrypt(image_bytes.getvalue())
    return encrypted_data

def decrypt_image_data(encrypted_data, cipher):
    decrypted_bytes = cipher.decrypt(encrypted_data)
    decrypted_image = Image.open(BytesIO(decrypted_bytes))
    return decrypted_image

# ------------------------
# Step 4: AI-based Anomaly Detection Simulation on Encrypted Data
# ------------------------
def detect_anomalies(encrypted_data):
    data_array = np.frombuffer(encrypted_data, dtype=np.uint8).reshape(-1, 1)
    model = IsolationForest(contamination=0.01)
    model.fit(data_array)
    predictions = model.predict(data_array)
    anomalies = predictions == -1
    print(f"Anomalies Detected: {np.sum(anomalies)} out of {len(data_array)} bytes")
    # For demonstration, just return True if no anomalies
    return np.sum(anomalies) == 0

# ------------------------
# Step 5: Performance Metrics Comparison & Display
# ------------------------
def compare_images(original, decrypted):
    original_np = np.array(original)
    decrypted_np = np.array(decrypted)
    mse_value = np.mean((original_np - decrypted_np) ** 2)
    psnr_value = float('inf') if mse_value == 0 else 20 * np.log10(255.0 / np.sqrt(mse_value))
    ssim_value = ssim(original_np, decrypted_np, win_size=3, channel_axis=2)
    print(f"MSE: {mse_value:.6f}")
    print(f"PSNR: {psnr_value:.2f} dB")
    print(f"SSIM: {ssim_value:.6f}")
    # Plot side-by-side images
    fig, axes = plt.subplots(1, 2, figsize=(12, 6))
    axes[0].imshow(original)
    axes[0].set_title("Original Image")
    axes[0].axis('off')
    axes[1].imshow(decrypted)
    axes[1].set_title("Decrypted Image")
    axes[1].axis('off')
    plt.show()

# ------------------------
# Main Execution Flow
# ------------------------
file_id = "1AVgok_S3UrCtlDvxsTc6ltAaPwcZGNMD"

if authenticate_user():
    image = load_image_from_drive(file_id)

    # Display Original Image
    plt.figure(figsize=(6,6))
    plt.imshow(image)
    plt.title("Original Image")
    plt.axis('off')
    plt.show()

    # Setup encryption
    key = Fernet.generate_key()
    cipher = Fernet(key)

    encrypted_data = encrypt_image_data(image, cipher)

    # Plot encrypted image data
    encrypted_array = np.frombuffer(encrypted_data, dtype=np.uint8)
    plt.figure(figsize=(10,2))
    plt.plot(encrypted_array, color='black')
    plt.title("Encrypted Image Data (Byte Representation)")
    plt.xlabel("Byte Index")
    plt.ylabel("Byte Value")
    plt.show()

    # AI-based Anomaly Detection on encrypted data
    if detect_anomalies(encrypted_data):
        print("No anomalies detected, proceeding with decryption.")
        decrypted_image = decrypt_image_data(encrypted_data, cipher)

        # Display decrypted image
        plt.figure(figsize=(6,6))
        plt.imshow(decrypted_image)
        plt.title("Decrypted Image")
        plt.axis('off')
        plt.show()

        # Compare original and decrypted images
        compare_images(image, decrypted_image)
    else:
        print("Anomalies detected! Transmission may be compromised.")
else:
    print("Access denied due to failed authentication.")

import requests
from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt
from cryptography.fernet import Fernet
import numpy as np
from skimage.metrics import structural_similarity as ssim
from sklearn.ensemble import IsolationForest
import random

# ------------------------
# Step 1: Authentication Simulation (placeholder)
# ------------------------
def authenticate_user():
    print("Authenticating user...")
    authenticated = True
    print("Authentication successful." if authenticated else "Authentication failed.")
    return authenticated

# ------------------------
# Step 2: Load image from Google Drive
# ------------------------
def load_image_from_drive(file_id):
    image_url = f"https://drive.google.com/uc?export=download&id={file_id}"
    response = requests.get(image_url)
    response.raise_for_status()
    image = Image.open(BytesIO(response.content))
    return image

# ------------------------
# Step 3: Encrypt and decrypt image data
# ------------------------
def encrypt_image_data(image, cipher):
    image_bytes = BytesIO()
    image.save(image_bytes, format=image.format)
    encrypted_data = cipher.encrypt(image_bytes.getvalue())
    return encrypted_data

def decrypt_image_data(encrypted_data, cipher):
    decrypted_bytes = cipher.decrypt(encrypted_data)
    decrypted_image = Image.open(BytesIO(decrypted_bytes))
    return decrypted_image

# ------------------------
# Step 4: Introduce anomaly into encrypted data (randomly flip 50% bytes)
# ------------------------
def introduce_anomaly(encrypted_data, anomaly_prob=0.001):
    data_array = bytearray(encrypted_data)
    for i in range(len(data_array)):
        if random.random() < anomaly_prob:
            data_array[i] = data_array[i] ^ 0xFF  # Flip bits for anomaly
    corrupted_data = bytes(data_array)
    return corrupted_data

# ------------------------
# Step 5: AI-based Anomaly Detection Simulation on Encrypted Data
# ------------------------
def detect_anomalies(encrypted_data):
    data_array = np.frombuffer(encrypted_data, dtype=np.uint8).reshape(-1, 1)
    model = IsolationForest(contamination=0.01, random_state=42)
    model.fit(data_array)
    predictions = model.predict(data_array)
    anomalies = predictions == -1
    print(f"Anomalies Detected: {np.sum(anomalies)} out of {len(data_array)} bytes")
    return np.sum(anomalies) == 0

# ------------------------
# Step 6: Performance Metrics Comparison & Display
# ------------------------
def compare_images(original, decrypted):
    original_np = np.array(original)
    decrypted_np = np.array(decrypted)
    mse_value = np.mean((original_np - decrypted_np) ** 2)
    psnr_value = float('inf') if mse_value == 0 else 20 * np.log10(255.0 / np.sqrt(mse_value))
    ssim_value = ssim(original_np, decrypted_np, win_size=3, channel_axis=2)
    print(f"MSE: {mse_value:.6f}")
    print(f"PSNR: {psnr_value:.2f} dB")
    print(f"SSIM: {ssim_value:.6f}")
    fig, axes = plt.subplots(1, 2, figsize=(12, 6))
    axes[0].imshow(original)
    axes[0].set_title("Original Image")
    axes[0].axis('off')
    axes[1].imshow(decrypted)
    axes[1].set_title("Decrypted Image")
    axes[1].axis('off')
    plt.show()

# ------------------------
# Main Execution Flow
# ------------------------
file_id = "1AVgok_S3UrCtlDvxsTc6ltAaPwcZGNMD"

if authenticate_user():
    image = load_image_from_drive(file_id)

    plt.figure(figsize=(6,6))
    plt.imshow(image)
    plt.title("Original Image")
    plt.axis('off')
    plt.show()

    key = Fernet.generate_key()
    cipher = Fernet(key)

    encrypted_data = encrypt_image_data(image, cipher)

    # Introduce anomaly randomly with probability 0.5 per byte
    corrupted_data = introduce_anomaly(encrypted_data, anomaly_prob=0.005)

    encrypted_array = np.frombuffer(corrupted_data, dtype=np.uint8)
    plt.figure(figsize=(10,2))
    plt.plot(encrypted_array, color='red')
    plt.title("Encrypted Image Data with Anomalies (Byte Representation)")
    plt.xlabel("Byte Index")
    plt.ylabel("Byte Value")
    plt.show()

    if detect_anomalies(corrupted_data):
        print("No anomalies detected, proceeding with decryption.")
        decrypted_image = decrypt_image_data(corrupted_data, cipher)

        plt.figure(figsize=(6,6))
        plt.imshow(decrypted_image)
        plt.title("Decrypted Image")
        plt.axis('off')
        plt.show()

        compare_images(image, decrypted_image)
    else:
        print("Anomalies detected! Transmission may be compromised.")
else:
    print("Access denied due to failed authentication.")

import requests
from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt
from cryptography.fernet import Fernet
import numpy as np
from skimage.metrics import structural_similarity as ssim
from sklearn.ensemble import IsolationForest
import random

# ------------------------
# Step 1: Authentication Simulation (placeholder)
# ------------------------
def authenticate_user():
    print("Authenticating user...")
    authenticated = True
    print("Authentication successful." if authenticated else "Authentication failed.")
    return authenticated

# ------------------------
# Step 2: Load image from Google Drive
# ------------------------
def load_image_from_drive(file_id):
    image_url = f"https://drive.google.com/uc?export=download&id={file_id}"
    response = requests.get(image_url)
    response.raise_for_status()
    image = Image.open(BytesIO(response.content))
    return image

# ------------------------
# Step 3: Encrypt and decrypt image data
# ------------------------
def encrypt_image_data(image, cipher):
    image_bytes = BytesIO()
    image.save(image_bytes, format=image.format)
    encrypted_data = cipher.encrypt(image_bytes.getvalue())
    return encrypted_data

def decrypt_image_data(encrypted_data, cipher):
    decrypted_bytes = cipher.decrypt(encrypted_data)
    decrypted_image = Image.open(BytesIO(decrypted_bytes))
    return decrypted_image

# ------------------------
# Step 4: Introduce anomaly into encrypted data (randomly flip 50% bytes)
# ------------------------
def introduce_anomaly(encrypted_data, anomaly_prob=0.5):
    data_array = bytearray(encrypted_data)
    for i in range(len(data_array)):
        if random.random() < anomaly_prob:
            data_array[i] = data_array[i] ^ 0xFF  # Flip bits to create anomaly
    corrupted_data = bytes(data_array)
    return corrupted_data

# ------------------------
# Step 5: AI-based Anomaly Detection Simulation on Encrypted Data
# ------------------------
def detect_anomalies(encrypted_data):
    data_array = np.frombuffer(encrypted_data, dtype=np.uint8).reshape(-1, 1)
    model = IsolationForest(contamination=0.01, random_state=42)
    model.fit(data_array)
    predictions = model.predict(data_array)
    anomalies = predictions == -1
    anomaly_count = np.sum(anomalies)
    normal_count = len(data_array) - anomaly_count

    print(f"Anomalies Detected: {anomaly_count} out of {len(data_array)} bytes")

    # Plot anomaly detection performance
    plt.figure(figsize=(6,4))
    plt.bar(['Normal', 'Anomalous'], [normal_count, anomaly_count], color=['green', 'red'])
    plt.title("Anomaly Detection Performance")
    plt.ylabel("Number of Bytes")
    plt.show()

    return anomaly_count == 0

# ------------------------
# Step 6: Performance Metrics Comparison & Display
# ------------------------
def compare_images(original, decrypted):
    original_np = np.array(original)
    decrypted_np = np.array(decrypted)
    mse_value = np.mean((original_np - decrypted_np) ** 2)
    psnr_value = float('inf') if mse_value == 0 else 20 * np.log10(255.0 / np.sqrt(mse_value))
    ssim_value = ssim(original_np, decrypted_np, win_size=3, channel_axis=2)
    print(f"MSE: {mse_value:.6f}")
    print(f"PSNR: {psnr_value:.2f} dB")
    print(f"SSIM: {ssim_value:.6f}")

    fig, axes = plt.subplots(1, 2, figsize=(12, 6))
    axes[0].imshow(original)
    axes[0].set_title("Original Image")
    axes[0].axis('off')
    axes[1].imshow(decrypted)
    axes[1].set_title("Decrypted Image")
    axes[1].axis('off')
    plt.show()

# ------------------------
# Main Execution Flow
# ------------------------
file_id = "1AVgok_S3UrCtlDvxsTc6ltAaPwcZGNMD"

if authenticate_user():
    image = load_image_from_drive(file_id)

    plt.figure(figsize=(6,6))
    plt.imshow(image)
    plt.title("Original Image")
    plt.axis('off')
    plt.show()

    key = Fernet.generate_key()
    cipher = Fernet(key)

    encrypted_data = encrypt_image_data(image, cipher)

    # Introduce anomaly randomly with probability 0.5 per byte
    corrupted_data = introduce_anomaly(encrypted_data, anomaly_prob=0.5)

    encrypted_array = np.frombuffer(corrupted_data, dtype=np.uint8)
    plt.figure(figsize=(10,2))
    plt.plot(encrypted_array, color='red')
    plt.title("Encrypted Image Data with Anomalies (Byte Representation)")
    plt.xlabel("Byte Index")
    plt.ylabel("Byte Value")
    plt.show()

    if detect_anomalies(corrupted_data):
        print("No anomalies detected, proceeding with decryption.")
        decrypted_image = decrypt_image_data(corrupted_data, cipher)

        plt.figure(figsize=(6,6))
        plt.imshow(decrypted_image)
        plt.title("Decrypted Image")
        plt.axis('off')
        plt.show()

        compare_images(image, decrypted_image)
    else:
        print("Anomalies detected! Transmission may be compromised.")
else:
    print("Access denied due to failed authentication.")

import requests
import pandas as pd
from io import BytesIO
from cryptography.fernet import Fernet
import numpy as np
from sklearn.ensemble import IsolationForest
import random

# ------------------------
# Authentication Simulation
# ------------------------
def authenticate_user():
    print("Authenticating user...")
    authenticated = True
    print("Authentication successful." if authenticated else "Authentication failed.")
    return authenticated

# ------------------------
# Load CSV file from Google Drive
# ------------------------
def load_csv_from_drive(file_id):
    csv_url = f"https://drive.google.com/uc?export=download&id={file_id}"
    response = requests.get(csv_url)
    response.raise_for_status()
    csv_data = response.content
    df = pd.read_csv(BytesIO(csv_data))
    return df, csv_data

# ------------------------
# Encrypt and decrypt CSV data
# ------------------------
def encrypt_data(data_bytes, cipher):
    encrypted_data = cipher.encrypt(data_bytes)
    return encrypted_data

def decrypt_data(encrypted_data, cipher):
    decrypted_bytes = cipher.decrypt(encrypted_data)
    return decrypted_bytes

# ------------------------
# Introduce anomaly into encrypted data (random bit flips)
# ------------------------
def introduce_anomaly(encrypted_data, anomaly_prob=0.5):
    data_array = bytearray(encrypted_data)
    for i in range(len(data_array)):
        if random.random() < anomaly_prob:
            data_array[i] ^= 0xFF
    corrupted_data = bytes(data_array)
    return corrupted_data

# ------------------------
# AI-based Anomaly Detection on encrypted data
# ------------------------
def detect_anomalies(encrypted_data):
    data_array = np.frombuffer(encrypted_data, dtype=np.uint8).reshape(-1, 1)
    model = IsolationForest(contamination=0.01, random_state=42)
    model.fit(data_array)
    predictions = model.predict(data_array)
    anomalies = predictions == -1
    anomaly_count = np.sum(anomalies)
    normal_count = len(data_array) - anomaly_count

    print(f"Anomalies Detected: {anomaly_count} out of {len(data_array)} bytes")

    # Plot anomaly detection results
    import matplotlib.pyplot as plt
    plt.figure(figsize=(6,4))
    plt.bar(['Normal', 'Anomalous'], [normal_count, anomaly_count], color=['green', 'red'])
    plt.title("Anomaly Detection Performance")
    plt.ylabel("Number of Bytes")
    plt.show()

    return anomaly_count == 0

# ------------------------
# Compare original and decrypted CSV bytes
# ------------------------
def compare_bytes(original_bytes, decrypted_bytes):
    original_np = np.frombuffer(original_bytes, dtype=np.uint8)
    decrypted_np = np.frombuffer(decrypted_bytes, dtype=np.uint8)
    mse_value = np.mean((original_np - decrypted_np) ** 2)
    print(f"MSE between original and decrypted CSV bytes: {mse_value:.6f}")

# ------------------------
# Main Execution Flow
# ------------------------
file_id = "1VVevnlWwnoybE9ykqpRvBsNxDm9jZrmj"  # Your CSV file ID

if authenticate_user():
    df, csv_bytes = load_csv_from_drive(file_id)
    print("Loaded CSV Data (head):")
    print(df.head())

    key = Fernet.generate_key()
    cipher = Fernet(key)

    encrypted_data = encrypt_data(csv_bytes, cipher)
    corrupted_data = introduce_anomaly(encrypted_data, anomaly_prob=0.5)

    if detect_anomalies(corrupted_data):
        print("No anomalies detected, proceeding with decryption.")
        decrypted_bytes = decrypt_data(corrupted_data, cipher)
        df_decrypted = pd.read_csv(BytesIO(decrypted_bytes))
        print("Decrypted CSV Data (head):")
        print(df_decrypted.head())
        compare_bytes(csv_bytes, decrypted_bytes)
    else:
        print("Anomalies detected! Transmission may be compromised.")
else:
    print("Access denied due to failed authentication.")

import matplotlib.pyplot as plt
import numpy as np

# Model names and colors + textures
models = ['Proposed', 'BM3D', 'DnCNN', 'Wavelet', 'FSIM', 'VIF']
colors = ['#2d6b9f', '#33691e', '#ad1457', '#ffab00', '#00838f', '#7c4dff']
hatches = ['', '///', 'xxx', '---', '\\\\\\', '***']

# Values from the table
mse =     [37.28, 40.00, 35.00, 38.00, 36.00, 39.50]
psnr =    [32.42, 31.50, 32.50, 31.80, 32.20, 32.00]
ssim =    [0.7869, 0.780, 0.800, 0.770, 0.790, 0.780]

def plot_bars(values, ylabel, title, filename):
    plt.figure(figsize=(4.75, 3.0))  # IEEE: ~3.5in wide single column, 7in double, 3in height
    bars = plt.bar(models, values, color=colors, edgecolor='black')
    for bar, hatch in zip(bars, hatches):
        bar.set_hatch(hatch)
    for i, v in enumerate(values):
        plt.text(i, v + (max(values)*0.01), f'{v:.3f}' if ylabel=='SSIM' else f'{v:.2f}', ha='center', va='bottom', fontsize=10)
    plt.ylabel(ylabel, fontsize=12)
    plt.title(title, fontsize=13, weight='bold')
    plt.xticks(rotation=15, fontsize=11)
    plt.tight_layout()
    plt.savefig(filename, dpi=300)
    plt.show()

# Plot each separately:
plot_bars(mse,  'MSE (lower better)', 'Performance Comparison: MSE', 'performance_mse_ieee.png')
plot_bars(psnr, 'PSNR (dB, higher better)', 'Performance Comparison: PSNR', 'performance_psnr_ieee.png')
plot_bars(ssim, 'SSIM (higher better)', 'Performance Comparison: SSIM', 'performance_ssim_ieee.png')